config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :continents, only: [:index]
  resources :countries, only: [:index]
  resources :locations, only: [:index]

  get 'about', to: 'pages#about'

  get 'locations/:url', to: 'locations#show', as: :location
  get 'continents/:continent_name', to: 'continents#show', as: :continent
  get 'countries/:country_name', to: 'countries#show', as: :country
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :locations
  has_many :countries

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :locations

  belongs_to :continent
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :continent
  belongs_to :country

  # attr_reader :location_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def show
    @country_name = params[:country_name]
    @country = Country.find_by(country_name: @country_name.downcase)

    @country_locations = Location.where("country_id = 3")
    @italy_locations = Location.where("country_id = 2")
    @usa_locations = Location.where("country_id = 1")
    @denmark_locations = Location.where("country_id = 4")

    # Navbar
    @asia_countries = Country.where("continent_id = '3'")
    @europe_countries = Country.where("continent_id = '2'")
    @namerica_countries = Country.where("continent_id = '1'")
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location_url = params[:url]
    @location = Location.find_by(url: @location_url)

    @locations = Location.all

    @location_random = Location.all.where("url != ?", current_location.url).sample.url

    # Navbar
    @asia_countries = Country.where("continent_id = '3'")
    @europe_countries = Country.where("continent_id = '2'")
    @namerica_countries = Country.where("continent_id = '1'")
  end

  private

  def current_location
    @current_location ||= Location.find_by(url: params[:url]) if params[:url]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # Navbar
    @asia_countries = Country.where("continent_id = '3'")
    @europe_countries = Country.where("continent_id = '2'")
    @namerica_countries = Country.where("continent_id = '1'")

    # Featured Locations
    @featured_locations = Location.where("featured = true")
  end

  def about
    # Navbar
    @asia_countries = Country.where("continent_id = '3'")
    @europe_countries = Country.where("continent_id = '2'")
    @namerica_countries = Country.where("continent_id = '1'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/_denmark.html.erb
<div class="country-show">
  <div class="horizontal-scroll">
    <% @denmark_locations.each do |l| %>
      <div class="banner">
        <%= link_to location_path(l.url) do %>
          <%= cl_image_tag ("thanh-travels/Copenhagen/#{l.url}-banner.jpg"), class: "scroll one" %>
          <div class="overlay">
            <h1><%= l.location_name %></h1>
            <br>
            <h2><%= l.country.country_name %>, <%= l.continent.continent_name %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="scroll-horizontally">
  <h4>Please scroll</h4>
  <i class="fas fa-arrow-right"></i>
</div>

app/views/countries/_italy.html.erb
<div class="country-show">
  <div class="horizontal-scroll">
    <% @italy_locations.each do |l| %>
      <div class="banner">
        <%= link_to location_path(l.url) do %>
          <%= image_tag ("#{l.url}-banner.jpg"), class: "scroll one" %>
          <div class="overlay">
            <h1><%= l.location_name %></h1>
            <br>
            <h2><%= l.country.country_name %>, <%= l.continent.continent_name %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="scroll-horizontally">
  <h4>Please scroll</h4>
  <i class="fas fa-arrow-right"></i>
</div>

app/views/countries/_malaysia.html.erb
<div class="country-show">
  <div class="horizontal-scroll">
    <% @country_locations.each do |l| %>
      <div class="banner">
        <%= link_to location_path(l.url) do %>
          <%= image_tag ("#{l.url}-banner.jpg"), class: "scroll one" %>
          <div class="overlay">
            <h1><%= l.location_name %></h1>
            <br>
            <h2><%= l.country.country_name %>, <%= l.continent.continent_name %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="scroll-horizontally">
  <h4>Please scroll</h4>
  <i class="fas fa-arrow-right"></i>
</div>

app/views/countries/_usa.html.erb
<div class="home-thanh-travels">
  <div class="horizontal-scroll">
    <% @usa_locations.each do |l| %>
      <div class="banner">
        <%= link_to location_path(l.url) do %>
          <%= image_tag ("#{l.url}-banner.jpg"), class: "scroll one" %>
          <div class="overlay">
            <h1><%= l.location_name %></h1>
            <br>
            <h2><%= l.country.country_name %>, <%= l.continent.continent_name %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="scroll-horizontally">
  <h4>Please scroll</h4>
  <i class="fas fa-arrow-right"></i>
</div>

app/views/countries/show.html.erb
<%= render "countries/#{@country_name}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/locations/_copenhagen.html.erb
<div class="country-tags">
  <h6>
    <%= @location.continent.continent_name %>
    >
    <%= link_to country_path(@location.country.country_name.downcase) do %>
      <%= @location.country.country_name %>
    <% end %>
  </h6>
</div>

<div class="location-show-banner" style="background-image: url(<%= asset_path "#{@location.url}-banner.jpg" %>)">
  <h1><%= @location.location_name.upcase %></h1>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-1.jpg"), class: "duo-horizontal-two" %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-2.jpg"), class: "duo-horizontal-three" %>
</div>

<div class="location-show-text text-center">
  <h4><em>"The real question is: How can I place make you feel at home in a couple of seconds? <br><br> Despite the cold weather, Copenhagen knows how to warm my heart."</em></h4>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/#{@location.url}-photo-vertical-1.jpg", :angle=>"auto_right", class: "vertical-alone") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-3.jpg"), class: "duo-horizontal-two" %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-4.jpg"), class: "duo-horizontal-three" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/#{@location.url}-photo-vertical-2.jpg", :angle=>"auto_right", class: "duo-vertical-first") %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-5.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-6.jpg", class: "horizontal-alone") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/#{@location.url}-photo-vertical-3.jpg", :angle=>"auto_right", class: "duo-vertical-first") %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-7.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/#{@location.url}-photo-vertical-4.jpg", :angle=>"auto_right", class: "duo-vertical-first") %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-8.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/#{@location.url}-photo-horizontal-9.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-10.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-11.jpg"), class: "horizontal-alone-two" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-12.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-13.jpg"), class: "duo-horizontal-two" %>
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-14.jpg"), class: "duo-horizontal-three" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/Copenhagen/copenhague-photo-horizontal-15.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/Copenhagen/copenhague-photo-vertical-5.jpg", :angle=>"auto_right", class: "vertical-alone") %>
</div>

app/views/locations/_deathvalley.html.erb
<div class="country-tags">
  <h6>
    <%= @location.continent.continent_name %>
    >
    <%= link_to country_path(@location.country.country_name.downcase) do %>
      <%= @location.country.country_name %>
    <% end %>
  </h6>
</div>

<div class="location-show-banner" style="background-image: url(<%= asset_path "#{@location.url}-banner.jpg" %>)">
  <h1><%= @location.location_name.upcase %></h1>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-1.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-text text-center">
  <h4><em>"This is what I love about the US. Exotic landscapes a few hours of road trip away."</em></h4>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-2.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-vertical-1.jpg"), class: "duo-vertical-first" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-5.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-3.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-4.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-vertical-3.jpg"), class: "duo-vertical-first" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-8.jpg"), class: "duo-horizontal-three" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-6.jpg"), class: "horizontal-alone" %>
</div>


<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-vertical-2.jpg"), class: "duo-vertical-first" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-9.jpg"), class: "horizontal-alone" %>
</div>

app/views/locations/_florence.html.erb
<div class="country-tags">
  <h6>
    <%= @location.continent.continent_name %>
    >
    <%= link_to country_path(@location.country.country_name.downcase) do %>
      <%= @location.country.country_name %>
    <% end %>
  </h6>
</div>

<div class="location-show-banner" style="background-image: url(<%= asset_path "#{@location.url}-banner.jpg" %>)">
  <h1><%= @location.location_name.upcase %></h1>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-1.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-text text-center">
  <h4><em>"Living here would be a privilege, to live in the remarkable past of the brightest minds. <br><br> But is that what the future holds?"</em></h4>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-1.jpg", :angle=>"auto_right", class: "vertical-alone") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-2.jpg", :angle=>"auto_right", class: "duo-horizontal-three") %>
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-3.jpg", :angle=>"auto_right", class: "duo-horizontal-three") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-2.jpg"), class: "horizontal-alone-two" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-3.jpg"), class: "duo-horizontal-two" %>
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-4.jpg"), class: "duo-horizontal-three" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-square-2.jpg"), class: "duo-horizontal-two" %>
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-square-1.jpg", :angle=>"auto_right", class: "duo-horizontal-three") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-5.jpg", :angle=>"auto_right", class: "vertical-alone") %>
</div>

<div class="location-show-big-panel-pano">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-pano-1.jpg"), class: "pano-first" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-5.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-6.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag ("thanh-travels/#{@location.location_name}/#{@location.url}-photo-horizontal-7.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-6.jpg", :angle=>"auto_right", class: "duo-horizontal-three") %>
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-7.jpg", :angle=>"auto_right", class: "duo-horizontal-three") %>
</div>

<div class="location-show-panel">
  <%= cl_image_tag("thanh-travels/#{@location.location_name}/#{@location.url}-photo-vertical-4.jpg", :angle=>"auto_right", class: "vertical-alone") %>
</div>

app/views/locations/_newportbeach.html.erb
<div class="country-tags">
  <h6>
    <%= @location.continent.continent_name %>
    >
    <%= link_to country_path(@location.country.country_name.downcase) do %>
      <%= @location.country.country_name %>
    <% end %>
  </h6>
</div>

<div class="location-show-banner" style="background-image: url(<%= asset_path "#{@location.url}-banner.jpg" %>)">
  <h1><%= @location.location_name.upcase %></h1>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-1.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-text text-center">
  <h4><em>"California, here we come. <br><br> That promise Orange Country made in movies and TV shows is not a lie."</em></h4>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-2.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-4.jpg"), class: "duo-vertical-first" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-5.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-6.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-7.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-8.jpg"), class: "duo-horizontal-two" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-9.jpg"), class: "duo-horizontal-three" %>
</div>

app/views/locations/_rawa.html.erb
<div class="country-tags">
  <h6>
    <%= @location.continent.continent_name %>
    >
    <%= link_to country_path(@location.country.country_name.downcase) do %>
      <%= @location.country.country_name %>
    <% end %>
  </h6>
</div>

<div class="location-show-banner" style="background-image: url(<%= asset_path "#{@location.url}-banner.jpg" %>)">
  <h1><%= @location.location_name.upcase %></h1>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-1.jpg"), class: "horizontal-alone" %>
</div>

<div class="location-show-text text-center">
  <h4><em>"If you’ve seen the movie The Beach, this could be a replica of that. When the sun brings out the translucid water, this place does look like paradise. <br> <br> But I’ve never wanted to live in these places. These places are traps, like ticking bombs, to reveal the weakest soul. Ultimately, taking us all in the depth of hell and debauchery."</em></h4>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-vertical-1.jpg"), class: "duo-vertical-first" %>
  <%= image_tag ("#{@location.url}-photo-horizontal-2.jpg"), class: "duo-horizontal-first" %>
</div>

<div class="location-show-panel-pano">
  <%= image_tag ("#{@location.url}-photo-pano-1.jpg"), class: "pano-first" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-vertical-2.jpg"), class: "duo-vertical-two" %>
  <%= image_tag ("#{@location.url}-photo-vertical-3.jpg"), class: "duo-vertical-three" %>
</div>

<div class="location-show-panel-pano">
  <%= image_tag ("#{@location.url}-photo-pano-2.jpg"), class: "pano-first" %>
</div>

<div class="location-show-panel">
  <%= image_tag ("#{@location.url}-photo-horizontal-3.jpg"), class: "horizontal-alone" %>
</div>

app/views/locations/show.html.erb
<%= render "locations/#{@location_url}" %>


<!-- Footer -->

<div class="location-show-footer">
  <div class="location-show-footer-text text-center">
    <h3>let's keep travelling</h3>
    <%= link_to location_path(@location_random) do %>
      <h1><em>THE WORLD</em></h1>
    <% end %>
  </div>

  <div class="location-show-footer-logo text-center">
    <%= image_tag ("logo.png"), class: "small-logo" %>
  </div>

</div>

app/views/pages/about.html.erb
<div class="about-content text-center">

  <div class="about-picture"></div>

  <div class="about-text">
    <p>I've spent most of my life between places. I was quite young when I started to realize that my travels would shape the way I think, the way I act. <br><br> I never had the desire to travel the whole world for an entire year. But I do have a dream and that is to find a place where I would feel at home. And this dream can't come true without the exploration, without the adventures and without the many travels. I wish I could stay in every place I go long enough so I could picture myself there. <br><br> These are my discoveries.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-thanh-travels">
  <div class="horizontal-scroll">
    <div class="banner">
      <%= link_to location_path(@featured_locations[0].url) do %>
        <%= image_tag ("#{@featured_locations[0].url}-banner.jpg"), class: "scroll one" %>
        <div class="overlay">
            <h1><%= @featured_locations[0].location_name %> </h1>
            <br>
            <h2><%= @featured_locations[0].country.country_name %>, <%= @featured_locations[0].continent.continent_name %></h2>
        </div>
      <% end %>

    </div>

    <div class="banner">
      <%= link_to location_path(@featured_locations[1].url) do %>
        <%= image_tag ("#{@featured_locations[1].url}-banner.jpg"), class: "scroll one" %>
        <div class="overlay">
          <h1><%= @featured_locations[1].location_name %></h1>
          <br>
          <h2><%= @featured_locations[1].country.country_name %>, <%= @featured_locations[1].continent.continent_name %></h2>
        </div>
      <% end %>
    </div>

    <div class="banner">
      <%= link_to location_path(@featured_locations[2].url) do %>
        <%= image_tag ("#{@featured_locations[2].url}-banner.jpg"), class: "scroll one" %>
        <div class="overlay">
          <h1><%= @featured_locations[2].location_name %></h1>
          <br>
          <h2><%= @featured_locations[2].country.country_name %>, <%= @featured_locations[2].continent.continent_name %></h2>
        </div>
      <% end %>
    </div>

    <div class="banner">
      <%= link_to location_path(@featured_locations[3].url) do %>
        <%= cl_image_tag ("thanh-travels/Copenhagen/#{@featured_locations[3].url}-banner.jpg"), class: "scroll one" %>
        <div class="overlay">
          <h1><%= @featured_locations[3].location_name %></h1>
          <br>
          <h2><%= @featured_locations[3].country.country_name %>, <%= @featured_locations[3].continent.continent_name %></h2>
        </div>
      <% end %>
    </div>

    <div class="banner">
      <%= link_to location_path(@featured_locations[4].url) do %>
        <%= image_tag ("#{@featured_locations[4].url}-banner.jpg"), class: "scroll one" %>
        <div class="overlay">
          <h1><%= @featured_locations[4].location_name %></h1>
          <br>
          <h2><%= @featured_locations[4].country.country_name %>, <%= @featured_locations[4].continent.continent_name %></h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="scroll-horizontally">
  <h4>Please scroll</h4>
  <i class="fas fa-arrow-right"></i>
</div>

app/views/shared/_footer.html.erb
<div class="location-show-footer-copyright text-center">
  <p>Made with love by Studio BOLE ©</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-thanh-travels">
  <%= link_to root_path do %>
    <%= image_tag ("logo.png"), class: "logo" %>
  <% end %>

  <div class="navbar-right-items">
    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <p>Asia</p>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <% @asia_countries.order(:country_name).each do |c| %>
          <li>
            <%= link_to country_path(c.country_name.downcase) do %>
              <%= c.country_name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <p>Europe</p>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <% @europe_countries.order(:country_name).each do |c| %>
          <li>
            <%= link_to country_path(c.country_name.downcase) do %>
              <%= c.country_name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <p>North America</p>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <% @namerica_countries.order(:country_name).each do |c| %>
          <li>
            <%= link_to country_path(c.country_name.downcase) do %>
              <%= c.country_name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="dropdown">
      <button>
        <%= link_to about_path do %>
            <p>About</p>
        <% end %>
      </button>
    </div>
  </div>
</div>

<!-- MOBILE HTML -->

<div class="navbar-mobile">
  <%= link_to root_path do %>
    <%= image_tag ("logo.png"), class: "logo" %>
  <% end %>

  <div class="navbar-right-items">
    <div id="mySidenav" class="sidenav">
      <a href="#" class="closebtn">&times;</a>
      <div class="navbar-continent">
        <h2>Asia</h2>
        <% @asia_countries.order(:country_name).each do |c| %>
          <%= link_to country_path(c.country_name.downcase) do %>
            <%= c.country_name %>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-continent">
        <h2>Europe</h2>
        <% @europe_countries.order(:country_name).each do |c| %>
          <%= link_to country_path(c.country_name.downcase) do %>
            <%= c.country_name %>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-continent">
        <h2>North America</h2>
        <% @namerica_countries.order(:country_name).each do |c| %>
          <%= link_to country_path(c.country_name.downcase) do %>
            <%= c.country_name %>
          <% end %>
        <% end %>
      </div>
      <div class="navbar-continent">
        <%= link_to about_path do %>
          <h2>About</h2>
        <% end %>
      </div>


    </div>
    <!-- Use any element to open the sidenav -->
    <span id="opensidenav"><i class="fas fa-bars"></i></span>
  </div>
</div>